### ISSUE TITLE
Error - AttributeError: 'Word2VecKeyedVectors' object has no attribute 'layer1_size'

### ISSUE THREAD

**Issue by NavneetSlalom** [RaRe-Technologies/movie-plots-by-genre#12]
hi, when I execute the following code, I get this error - AttributeError: 'Word2VecKeyedVectors' object has no attribute 'layer1_size'
%%time
X_train_word_average = word_averaging_list(wv,train_tokenized)
X_test_word_average = word_averaging_list(wv,test_tokenized)

The previous code - wv.layer1_size results in AttributeError: 'Word2VecKeyedVectors' object has no attribute 'layer1_size'

How can I resolve these errors?

**Comment by menshikh-iv** [comment]
Hello @NavneetSlalom, downgrade gensim version to `0.12.4` (looks actual for this notebook)

**Comment by NavneetSlalom** [comment]
Any compatibility or example to do the same with latest gensim version?

**Comment by menshikh-iv** [comment]
@NavneetSlalom no compatibility here (this was a very long time ago, `0.12.4` too old). 

You can modify code in notebook: 
- replace `wv.layer1_size` to `wv.vector_size`
- replace `genremodels[i].train(  slist, total_examples=len(slist) )` to `genremodels[i].train(slist, total_examples=len(slist), epochs=genremodels[i].epochs)`

I'm not sure that this list is full, I checked only before WMD part.

**Comment by NavneetSlalom** [comment]
Thanks for responding. Is there any latest example on how to use word2vec for classification problems?

**Comment by menshikh-iv** [comment]
@NavneetSlalom In the same way as in notebook :)

**Comment by NavneetSlalom** [comment]
Since downgrading gensim is not an option for me, can you please confirm that the following code will achieve the same i.e. calculate document vector:

#function to convert word tokens to document vector
def document_vector(word2vec_model, doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc if word in word2vec_model.wv.vocab]
    return np.mean(word2vec_model[doc], axis=0)


#document vector
avg_wv_train_features =[]
for doc in df['Narr']: #look up each doc in model
    avg_wv_train_features.append(document_vector(wv, doc))

later I am passing avg_wv_train_features to the classifier.

Thanks in advance!

**Comment by menshikh-iv** [comment]
@NavneetSlalom yes, I confirm, this is a possible way.

**Comment by NavneetSlalom** [comment]
Thanks!

I am getting an accuracy of .28 using SVM and GloVe. Other than doc2vec, is there any other option I can try?

**Comment by menshikh-iv** [comment]
FastText (as the mean of embeddings), LsiMode, LdaModel.
